Add initla client go sdk prototype
hyperledger-labs/fabric-private-chaincode pull request #452
Opened 2020-10-20 21:02 UTC by mbrandenburger

Signed-off-by: bur <bur@zurich.ibm.com>

**What this PR does / why we need it**:

- initial go sdk extension for FPC that hides the FPC transaction flow
  from the user
- integrate with test-network

**Which issue(s) this PR fixes**:

Fixes #289 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing changes and/or breaks backward compatability?**:

```

2020-10-21 22:00 UTC, mbrandenburger commented
Note that eecb1cd relies on a little modification at the go sdk. Opened a [PR](https://github.com/hyperledger/fabric-sdk-go/pull/153)

2020-10-22 12:40 UTC, mbrandenburger commented
PR was already merged!

2020-10-23 00:11 UTC, g2flyer requested changes
In general looks very nice regarding the user-facing API.  I have a number of observations regarding implementation but most of the issue might be better addressed elsewhere (primary concern is that there are some issues like interface between c and go (issue #412) and encoding/decoding, formats of request/response we seem to make somewhat implicit which i think we should make a bit more explcit/consciously ...). For actual PR, assuming you are happy with my clickable suggestions, themain concern is that it doesn't build

2020-10-23 17:29 UTC, bvavala commented
>  but most of the issue might be better addressed elsewhere (primary concern is that there are some issues like interface between c and go (issue #412) and encoding/decoding, formats of request/response we seem to make somewhat implicit which i think we should make a bit more explcit/consciously ...). 

I agree that these could be better addressed elsewhere, and I would add _later_ after getting the next release out.

2020-10-23 17:37 UTC, g2flyer commented
> I agree that these could be better addressed elsewhere, and I would add _later_ after getting the next release out.

If we don't agree on these encodings, interfaces and types (either explicitly or impliciltly) then there will be no next release?

2020-10-23 18:02 UTC, bvavala commented
> > I agree that these could be better addressed elsewhere, and I would add _later_ after getting the next release out.
> 
> If we don't agree on these encodings, interfaces and types (either explicitly or impliciltly) then there will be no next release?

Interfaces and protobufs are already defined, there is no need (at least at this point) for additional details -- hopefully this matches with your definition of "implicit" agreement.
The components being implemented are already part of the next release, and match the design.

2020-10-23 18:42 UTC, g2flyer commented
> Interfaces and protobufs are already defined,

The interfaces i was referring to is regarding #421 which we haven't designed.  Regarding protobufs, we forgot to define message format for (encrypted) fpc chaincode invocations (request and response).  Our spec also omitted the encoding of messages between client and fpc_stub.  We agreed in yesterday's call verbally on that encoding (i.e., base64-encoding of binary-serialization of protobuf objects), my point was only that we might also simply document that (and remove the misleading reference to json-protobuf). Anyway, i can do an AR on myself to create a PR which creates a proposal for the missing protobufs and does the small fix to interfaces.md regarding the encoding.

2020-10-27 17:13 UTC, mbrandenburger commented on go.mod
> +replace github.com/hyperledger/fabric-sdk-go => ../../hyperledger/fabric-sdk-go
will remove

2020-10-27 17:14 UTC, mbrandenburger commented on client_sdk/go/fpc/lifecycle.go
> +
true, let's keep it there for the moment. I might move the createEnclave command there; otherwise we remove it later when doing a proper cleanup.

2020-10-27 17:16 UTC, mbrandenburger commented on client_sdk/go/fpc/contract.go
> +		c.cachedChaincodeEncryptionKey = ccKeyBytes
yes good catch!

2020-10-27 17:18 UTC, mbrandenburger commented on client_sdk/go/fpc/contract.go
> +func (c *Contract) prepareChaincodeInvocation(name string, args []string, resultEncryptionKey []byte) (string, error) {
Good point, let me add a todo 
```suggestion
// TODO better move to TX. crypto lib?! TBD
func (c *Contract) prepareChaincodeInvocation(name string, args []string, resultEncryptionKey []byte) (string, error) {
```

2020-10-27 17:20 UTC, mbrandenburger commented on client_sdk/go/fpc/contract.go
> +	return Decrypt(response.ResponseData, resultEncryptionKey)
```suggestion
        // TODO maybe move this to a sub-function like prepareChaincodeInvocation?! TBD
	response, err := utils.UnmarshalResponse(responseBytes)
	if err != nil {
		return nil, err
	}

	// decrypt result
	return Decrypt(response.ResponseData, resultEncryptionKey)
```

2020-10-27 17:35 UTC, g2flyer commented on internal/utils/utils.go
> +// TODO replace this with a proto? TBD
protobufs will be defined in #453 ....

2020-10-27 17:37 UTC, g2flyer commented on client_sdk/go/fpc/lifecycle.go
> +
it's a bit confusing to have it hear, in particular with the API in the name and below another type which actually _does_ define an API.  But if you promise to clean it up sooner than later .... ;-)

2020-10-27 20:49 UTC, bvavala approved these changes
good overall.
I can see some discrepancies going forward -- mainly the client/chaincode protocol -- but that's fine. We'll reconcile these in upcoming PRs.

2020-10-27 22:30 UTC, g2flyer approved these changes
Ok, now `make build test` works and documented steps in README also all work. There is a bug in client-sdk test program but will fix that in separate PR and merge this one ...

2020-10-27 22:31 UTC, merged